name: price_pilot
description: A price comparison app for ride-hailing services.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^5.4.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  mobile_scanner: ^3.5.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true 